# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphics.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_painter(object):
    def setupUi(self, painter):
        painter.setObjectName("painter")
        painter.resize(806, 827)
        self.centralwidget = QtWidgets.QWidget(painter)
        self.centralwidget.setObjectName("centralwidget")
        self.koff_c = QtWidgets.QLineEdit(self.centralwidget)
        self.koff_c.setGeometry(QtCore.QRect(430, 580, 110, 24))
        self.koff_c.setObjectName("koff_c")
        self.lab_C = QtWidgets.QLabel(self.centralwidget)
        self.lab_C.setGeometry(QtCore.QRect(440, 550, 68, 16))
        self.lab_C.setObjectName("lab_C")
        self.koff_b = QtWidgets.QLineEdit(self.centralwidget)
        self.koff_b.setGeometry(QtCore.QRect(300, 580, 110, 24))
        self.koff_b.setObjectName("koff_b")
        self.draw_graphics = QtWidgets.QPushButton(self.centralwidget)
        self.draw_graphics.setEnabled(True)
        self.draw_graphics.setGeometry(QtCore.QRect(11, 738, 701, 51))
        self.draw_graphics.setToolTipDuration(-1)
        self.draw_graphics.setObjectName("draw_graphics")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(11, 11, 781, 441))
        self.graphicsView.setObjectName("graphicsView")
        self.lab_B = QtWidgets.QLabel(self.centralwidget)
        self.lab_B.setGeometry(QtCore.QRect(310, 550, 67, 16))
        self.lab_B.setObjectName("lab_B")
        self.koff_a = QtWidgets.QLineEdit(self.centralwidget)
        self.koff_a.setGeometry(QtCore.QRect(170, 580, 110, 24))
        self.koff_a.setObjectName("koff_a")
        self.lab_A = QtWidgets.QLabel(self.centralwidget)
        self.lab_A.setGeometry(QtCore.QRect(180, 550, 68, 16))
        self.lab_A.setObjectName("lab_A")
        self.lab_left = QtWidgets.QLabel(self.centralwidget)
        self.lab_left.setGeometry(QtCore.QRect(11, 491, 125, 16))
        self.lab_left.setObjectName("lab_left")
        self.left = QtWidgets.QLineEdit(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(11, 514, 110, 24))
        self.left.setObjectName("left")
        self.rigth = QtWidgets.QLineEdit(self.centralwidget)
        self.rigth.setGeometry(QtCore.QRect(10, 570, 110, 24))
        self.rigth.setObjectName("rigth")
        self.label_rigth = QtWidgets.QLabel(self.centralwidget)
        self.label_rigth.setGeometry(QtCore.QRect(11, 545, 132, 16))
        self.label_rigth.setObjectName("label_rigth")
        painter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(painter)
        self.statusbar.setObjectName("statusbar")
        painter.setStatusBar(self.statusbar)

        self.retranslateUi(painter)
        QtCore.QMetaObject.connectSlotsByName(painter)

    def retranslateUi(self, painter):
        _translate = QtCore.QCoreApplication.translate
        painter.setWindowTitle(_translate("painter", "MainWindow"))
        self.lab_C.setText(_translate("painter", "C"))
        self.draw_graphics.setText(_translate("painter", "Нарисовать график"))
        self.lab_B.setText(_translate("painter", "B"))
        self.lab_A.setText(_translate("painter", "A"))
        self.lab_left.setText(_translate("painter", "левая граница"))
        self.label_rigth.setText(_translate("painter", "правая граница "))
from pyqtgraph import PlotWidget
